"""
Cortex KnowledgeBase - Wiki-based knowledge management

Core abstraction for the knowledge base:
- Manages wiki directory structure
- Article CRUD with backlink tracking
- Semantic search across wiki content
- Index generation and maintenance

Directory structure:
    wiki/
    ├── index.md              # Auto-generated index
    ├── concepts/             # Concept articles
    ├── summaries/            # Document summaries
    └── outputs/              # Generated outputs
"""

import os
import re
import json
import time
from pathlib import Path
from typing import List, Dict, Optional, Tuple
from dataclasses import dataclass, field
import logging

logger = logging.getLogger(__name__)


@dataclass
class Article:
    """A wiki article"""
    path: str           # Relative path within wiki (e.g., "concepts/transformers.md")
    title: str          # Extracted from first heading or filename
    content: str        # Full markdown content
    created_at: float = field(default_factory=time.time)
    updated_at: float = field(default_factory=time.time)
    word_count: int = 0
    backlinks: List[str] = field(default_factory=list)  # Articles linking here
    tags: List[str] = field(default_factory=list)
    
    @property
    def filename(self) -> str:
        return os.path.basename(self.path)
    
    @property
    def category(self) -> str:
        parts = self.path.split("/")
        return parts[0] if len(parts) > 1 else ""


class KnowledgeBase:
    """
    Manages a wiki-based knowledge base.
    """
    
    def __init__(
        self,
        wiki_path: str,
        raw_path: str,
        memory=None,
        outputs_path: Optional[str] = None,
    ):
        self.wiki_path = Path(wiki_path).resolve()
        self.raw_path = Path(raw_path).resolve()
        self.outputs_path = Path(outputs_path or str(self.wiki_path / "outputs")).resolve()
        self.memory = memory
        self._backlinks: Dict[str, List[str]] = {}  # article -> [linking articles]
        
        self._ensure_structure()
        self._load_backlinks()
    
    def _ensure_structure(self):
        """Create wiki directory structure if it doesn't exist"""
        dirs = [
            self.wiki_path,
            self.wiki_path / "concepts",
            self.wiki_path / "summaries", 
            self.wiki_path / "outputs",
            self.raw_path,
            self.raw_path / "papers",
            self.raw_path / "articles",
            self.raw_path / "repos",
            self.raw_path / "images",
            self.outputs_path,
        ]
        for d in dirs:
            d.mkdir(parents=True, exist_ok=True)
        
        # Create index.md if it doesn't exist
        index_path = self.wiki_path / "index.md"
        if not index_path.exists():
            index_path.write_text("# Knowledge Base Index\n\n_Auto-generated by Cortex_\n\n")
    
    # === Article CRUD ===
    
    def get_article(self, path: str) -> Optional[Article]:
        """Read an article from the wiki"""
        full_path = self._resolve_wiki_path(path)
        if not full_path or not full_path.exists():
            return None
        
        content = full_path.read_text()
        title = self._extract_title(content, full_path.name)
        word_count = len(content.split())
        
        return Article(
            path=str(full_path.relative_to(self.wiki_path)),
            title=title,
            content=content,
            word_count=word_count,
            backlinks=self._backlinks.get(str(full_path.relative_to(self.wiki_path)), []),
        )
    
    def write_article(self, path: str, content: str) -> Article:
        """Write an article to the wiki"""
        full_path = self._resolve_wiki_path(path)
        if not full_path:
            raise ValueError(f"Invalid wiki path: {path}")
        
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content)
        
        title = self._extract_title(content, full_path.name)
        word_count = len(content.split())
        
        article = Article(
            path=str(full_path.relative_to(self.wiki_path)),
            title=title,
            content=content,
            word_count=word_count,
        )
        
        # Update memory if available
        if self.memory:
            try:
                self.memory.add(
                    content=f"Article: {title} - {content[:200]}...",
                    entry_type="article",
                    importance=0.7,
                    metadata={"path": article.path, "title": title},
                )
            except Exception as e:
                logger.warning(f"Failed to store article in memory: {e}")
        
        return article
    
    def delete_article(self, path: str) -> bool:
        """Delete an article from the wiki"""
        full_path = self._resolve_wiki_path(path)
        if full_path and full_path.exists():
            full_path.unlink()
            self._backlinks.pop(str(full_path.relative_to(self.wiki_path)), None)
            return True
        return False
    
    def list_articles(self, category: Optional[str] = None) -> List[Article]:
        """List all articles, optionally filtered by category"""
        search_path = self.wiki_path / category if category else self.wiki_path
        articles = []
        
        for md_file in search_path.rglob("*.md"):
            if md_file.name == "index.md":
                continue
            article = self.get_article(str(md_file.relative_to(self.wiki_path)))
            if article:
                articles.append(article)
        
        return sorted(articles, key=lambda a: a.updated_at, reverse=True)
    
    # === Search ===
    
    def search(self, query: str, limit: int = 10) -> List[Tuple[Article, float]]:
        """Search wiki articles semantically"""
        # Try memory-based search first
        if self.memory:
            try:
                results = self.memory.retrieve(query, limit=limit * 2)
                articles_with_scores = []
                
                for entry in results:
                    path = entry.metadata.get("path") if hasattr(entry, 'metadata') else None
                    if path:
                        article = self.get_article(path)
                        if article:
                            articles_with_scores.append((article, entry.importance if hasattr(entry, 'importance') else 0.5))
                
                if articles_with_scores:
                    articles_with_scores.sort(key=lambda x: x[1], reverse=True)
                    return articles_with_scores[:limit]
            except Exception as e:
                logger.warning(f"Memory search failed, falling back to keyword: {e}")
        
        # Fallback: keyword search
        return self._keyword_search(query, limit)
    
    def _keyword_search(self, query: str, limit: int) -> List[Tuple[Article, float]]:
        """Simple keyword search fallback"""
        query_words = set(query.lower().split())
        results = []
        
        for article in self.list_articles():
            content_words = set(article.content.lower().split())
            overlap = len(query_words & content_words)
            if overlap > 0:
                score = overlap / len(query_words)
                results.append((article, score))
        
        results.sort(key=lambda x: x[1], reverse=True)
        return results[:limit]
    
    # === Backlinks ===
    
    def get_backlinks(self, path: str) -> List[str]:
        """Get articles that link to the given article"""
        return self._backlinks.get(path, [])
    
    def update_backlinks(self):
        """Rebuild the entire backlink graph"""
        self._backlinks = {}
        
        for article in self.list_articles():
            links = self._extract_links(article.content)
            for link in links:
                if link not in self._backlinks:
                    self._backlinks[link] = []
                if article.path not in self._backlinks[link]:
                    self._backlinks[link].append(article.path)
        
        # Save backlinks
        config_dir = self.wiki_path.parent / ".cortex"
        config_dir.mkdir(parents=True, exist_ok=True)
        backlinks_path = config_dir / "backlinks.json"
        backlinks_path.write_text(json.dumps(self._backlinks, indent=2))
    
    def _extract_links(self, content: str) -> List[str]:
        """Extract wiki links from markdown content"""
        links = []
        
        # Standard markdown links: [text](path.md)
        for match in re.finditer(r'\[([^\]]+)\]\(([^)]+\.md)\)', content):
            links.append(match.group(2))
        
        # Wikilinks: [[path]]
        for match in re.finditer(r'\[\[([^\]]+)\]\]', content):
            link = match.group(1)
            if not link.endswith('.md'):
                link += '.md'
            links.append(link)
        
        return links
    
    # === Index ===
    
    def generate_index(self) -> str:
        """Generate the wiki index.md"""
        articles = self.list_articles()
        
        # Group by category
        by_category: Dict[str, List[Article]] = {}
        for article in articles:
            cat = article.category or "uncategorized"
            if cat not in by_category:
                by_category[cat] = []
            by_category[cat].append(article)
        
        lines = ["# Knowledge Base Index\n", ""]
        lines.append(f"_Last updated: {time.strftime('%Y-%m-%d %H:%M')}_\n")
        lines.append(f"_Total articles: {len(articles)}_  ")
        lines.append(f"_Total words: {sum(a.word_count for a in articles):,}_\n")
        lines.append("---\n")
        
        for category in sorted(by_category.keys()):
            lines.append(f"\n## {category.title()}\n")
            for article in sorted(by_category[category], key=lambda a: a.title):
                backlink_count = len(self.get_backlinks(article.path))
                lines.append(
                    f"- [{article.title}]({article.path}) "
                    f"({article.word_count:,} words"
                    f"{', ' + str(backlink_count) + ' backlinks' if backlink_count else ''})"
                )
        
        index_content = "\n".join(lines)
        self.write_article("index.md", index_content)
        return index_content
    
    # === Raw Document Access ===
    
    def get_raw_file(self, path: str) -> Optional[str]:
        """Read a raw source file"""
        full_path = self._resolve_raw_path(path)
        if full_path and full_path.exists():
            return full_path.read_text()
        return None
    
    def list_raw_files(self) -> List[Path]:
        """List all raw files"""
        return list(self.raw_path.rglob("*"))
    
    # === Helpers ===
    
    def _resolve_wiki_path(self, path: str) -> Optional[Path]:
        """Resolve a wiki path safely, preventing path traversal"""
        full_path = (self.wiki_path / path).resolve()
        if not str(full_path).startswith(str(self.wiki_path)):
            return None  # Path traversal attempt
        return full_path
    
    def _resolve_raw_path(self, path: str) -> Optional[Path]:
        """Resolve a raw path safely, preventing path traversal"""
        full_path = (self.raw_path / path).resolve()
        if not str(full_path).startswith(str(self.raw_path)):
            return None
        return full_path
    
    def _extract_title(self, content: str, filename: str) -> str:
        """Extract title from first heading or filename"""
        match = re.search(r'^#\s+(.+)$', content, re.MULTILINE)
        if match:
            return match.group(1).strip()
        return filename.replace('.md', '').replace('-', ' ').title()
    
    def _load_backlinks(self):
        """Load backlinks from file"""
        config_dir = self.wiki_path.parent / ".cortex"
        backlinks_path = config_dir / "backlinks.json"
        if backlinks_path.exists():
            try:
                self._backlinks = json.loads(backlinks_path.read_text())
            except (json.JSONDecodeError, IOError):
                self._backlinks = {}
    
    def get_stats(self) -> Dict:
        """Get knowledge base statistics"""
        articles = self.list_articles()
        return {
            "total_articles": len(articles),
            "total_words": sum(a.word_count for a in articles),
            "categories": list(set(a.category for a in articles if a.category)),
            "raw_files": len(list(self.raw_path.rglob("*"))),
            "backlink_count": sum(len(v) for v in self._backlinks.values()),
        }
